# Generated by Django 3.0.5 on 2020-05-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
