version: "3.7"

services:
  ##
  # Databases
  ##
  postgres:
      image: postgres:12.0-alpine
      container_name: postgresdb
      logging:
        driver: none
      volumes:
        - ./docker/bd/postgres:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: django
        POSTGRES_DB: django
  redis:
      image: redis:5.0.6
      container_name: redis
      logging:
        driver: none
      volumes:
        - ./docker/bd/redis:/data
      ports:
        - "6379:6379"
  ##
  # Backend services
  ##
  api:
    container_name: delivery-meal-api
    build:
      context: .
    volumes:
       - "./docker/wait-for-postgres.sh:/wait-for-postgres.sh"
       - ".:/usr/src/app"
    command: "/wait-for-postgres.sh postgres python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file: 
       - ./.env.example
