version: "3.7"

services:
  ##
  # Databases
  ##
  postgres:
      image: postgres:12.0-alpine
      container_name: postgresdb
      logging:
        driver: none
      volumes:
        - ./docker/bd/postgres:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: django
        POSTGRES_DB: django_test
  ##
  # Backend services
  ##
  api:
    container_name: delivery-meal-api
    build:
      context: .
    volumes:
       - "./docker/wait-for-it.sh:/wait-for-it.sh"
       - ".:/usr/src/app"
    command: "/wait-for-it.sh postgres:5432 -t 30 -- python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file: 
       - ./.env.example
  ##
  # Frontend services
  ##
  web:
    container_name: delivery-meal-web
    build:
      context: ./frontend
    volumes:
       - "./frontend:/usr/src/app"
       - '/usr/src/app/node_modules'
    command: "npm start"
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment: 
      CHOKIDAR_USEPOLLING: "true"
      CI: "true" 