# Generated by Django 3.0.5 on 2020-05-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
    ]
